#!/usr/bin/env bats
# Tests for backup.sh script (generated by install.sh)
# Run with: bats tests/test_backup.bats

# ─────────────────────────────────────────────────────────────
# Tests for date-based backup type determination
# ─────────────────────────────────────────────────────────────

@test "monthly backup on first day of month" {
    DAY_OF_MONTH="01"
    DAY_OF_WEEK="1"
    
    if [ "$DAY_OF_MONTH" = "01" ]; then
        TYPE="monthly"
    elif [ "$DAY_OF_WEEK" = "7" ]; then
        TYPE="weekly"
    else
        TYPE="daily"
    fi
    
    [ "$TYPE" = "monthly" ]
}

@test "weekly backup on Sunday" {
    DAY_OF_MONTH="15"
    DAY_OF_WEEK="7"
    
    if [ "$DAY_OF_MONTH" = "01" ]; then
        TYPE="monthly"
    elif [ "$DAY_OF_WEEK" = "7" ]; then
        TYPE="weekly"
    else
        TYPE="daily"
    fi
    
    [ "$TYPE" = "weekly" ]
}

@test "daily backup on normal day" {
    DAY_OF_MONTH="15"
    DAY_OF_WEEK="3"
    
    if [ "$DAY_OF_MONTH" = "01" ]; then
        TYPE="monthly"
    elif [ "$DAY_OF_WEEK" = "7" ]; then
        TYPE="weekly"
    else
        TYPE="daily"
    fi
    
    [ "$TYPE" = "daily" ]
}

@test "monthly takes precedence over Sunday" {
    # First of month that's also a Sunday
    DAY_OF_MONTH="01"
    DAY_OF_WEEK="7"
    
    if [ "$DAY_OF_MONTH" = "01" ]; then
        TYPE="monthly"
    elif [ "$DAY_OF_WEEK" = "7" ]; then
        TYPE="weekly"
    else
        TYPE="daily"
    fi
    
    [ "$TYPE" = "monthly" ]
}

# ─────────────────────────────────────────────────────────────
# Tests for backup filename generation
# ─────────────────────────────────────────────────────────────

@test "monthly backup filename format" {
    DATE="2024-01-01"
    TYPE="monthly"
    NAME="paperless-monthly-${DATE}.zip"
    
    [ "$NAME" = "paperless-monthly-2024-01-01.zip" ]
}

@test "weekly backup filename format" {
    DATE="2024-01-07"
    TYPE="weekly"
    NAME="paperless-weekly-${DATE}.zip"
    
    [ "$NAME" = "paperless-weekly-2024-01-07.zip" ]
}

@test "daily backup filename format" {
    DATE="2024-01-15"
    TYPE="daily"
    NAME="paperless-daily-${DATE}.zip"
    
    [ "$NAME" = "paperless-daily-2024-01-15.zip" ]
}

# ─────────────────────────────────────────────────────────────
# Tests for rclone remote upload condition
# ─────────────────────────────────────────────────────────────

@test "rclone upload enabled when remote configured" {
    RCLONE_REMOTE="Gdrive"
    
    if [ -n "$RCLONE_REMOTE" ]; then
        should_upload="true"
    else
        should_upload="false"
    fi
    
    [ "$should_upload" = "true" ]
}

@test "rclone upload disabled when remote empty" {
    RCLONE_REMOTE=""
    
    if [ -n "$RCLONE_REMOTE" ]; then
        should_upload="true"
    else
        should_upload="false"
    fi
    
    [ "$should_upload" = "false" ]
}

# ─────────────────────────────────────────────────────────────
# Tests for GitHub backup condition
# ─────────────────────────────────────────────────────────────

@test "GitHub backup enabled when both repo and passphrase set" {
    GITHUB_BACKUP_REPO="user/backup-repo"
    ENCRYPTION_PASSPHRASE="secret123"
    
    if [ -n "$GITHUB_BACKUP_REPO" ] && [ -n "$ENCRYPTION_PASSPHRASE" ]; then
        should_backup="true"
    else
        should_backup="false"
    fi
    
    [ "$should_backup" = "true" ]
}

@test "GitHub backup disabled when repo empty" {
    GITHUB_BACKUP_REPO=""
    ENCRYPTION_PASSPHRASE="secret123"
    
    if [ -n "$GITHUB_BACKUP_REPO" ] && [ -n "$ENCRYPTION_PASSPHRASE" ]; then
        should_backup="true"
    else
        should_backup="false"
    fi
    
    [ "$should_backup" = "false" ]
}

@test "GitHub backup disabled when passphrase empty" {
    GITHUB_BACKUP_REPO="user/backup-repo"
    ENCRYPTION_PASSPHRASE=""
    
    if [ -n "$GITHUB_BACKUP_REPO" ] && [ -n "$ENCRYPTION_PASSPHRASE" ]; then
        should_backup="true"
    else
        should_backup="false"
    fi
    
    [ "$should_backup" = "false" ]
}

# ─────────────────────────────────────────────────────────────
# Tests for healthchecks.io integration
# ─────────────────────────────────────────────────────────────

@test "healthcheck URL ping enabled when URL set" {
    HEALTHCHECK_URL="https://hc-ping.com/abc123"
    
    if [ -n "$HEALTHCHECK_URL" ]; then
        should_ping="true"
    else
        should_ping="false"
    fi
    
    [ "$should_ping" = "true" ]
}

@test "healthcheck URL ping disabled when URL empty" {
    HEALTHCHECK_URL=""
    
    if [ -n "$HEALTHCHECK_URL" ]; then
        should_ping="true"
    else
        should_ping="false"
    fi
    
    [ "$should_ping" = "false" ]
}

@test "healthcheck start URL format" {
    HEALTHCHECK_URL="https://hc-ping.com/abc123"
    START_URL="${HEALTHCHECK_URL}/start"
    
    [ "$START_URL" = "https://hc-ping.com/abc123/start" ]
}

@test "healthcheck fail URL format" {
    HEALTHCHECK_URL="https://hc-ping.com/abc123"
    FAIL_URL="${HEALTHCHECK_URL}/fail"
    
    [ "$FAIL_URL" = "https://hc-ping.com/abc123/fail" ]
}

# ─────────────────────────────────────────────────────────────
# Tests for backup rotation retention periods
# ─────────────────────────────────────────────────────────────

@test "daily backups retention is 7 days" {
    DAILY_RETENTION="7d"
    [ "$DAILY_RETENTION" = "7d" ]
}

@test "weekly backups retention is 28 days" {
    WEEKLY_RETENTION="28d"
    [ "$WEEKLY_RETENTION" = "28d" ]
}

@test "monthly backups retention is 90 days" {
    MONTHLY_RETENTION="90d"
    [ "$MONTHLY_RETENTION" = "90d" ]
}

# ─────────────────────────────────────────────────────────────
# Tests for encrypted backup file naming
# ─────────────────────────────────────────────────────────────

@test "encrypted backup filename format" {
    NAME="paperless-daily-2024-01-15.zip"
    ENCRYPTED="${NAME}.enc"
    
    [ "$ENCRYPTED" = "paperless-daily-2024-01-15.zip.enc" ]
}

# ─────────────────────────────────────────────────────────────
# Tests for rclone backup path construction
# ─────────────────────────────────────────────────────────────

@test "rclone daily backup path" {
    RCLONE_REMOTE="Gdrive"
    RCLONE_BACKUP_DIR="Backups/Paperless"
    TYPE="daily"
    
    DEST="$RCLONE_REMOTE:$RCLONE_BACKUP_DIR/$TYPE/"
    
    [ "$DEST" = "Gdrive:Backups/Paperless/daily/" ]
}

@test "rclone weekly backup path" {
    RCLONE_REMOTE="Dropbox"
    RCLONE_BACKUP_DIR="Backups/Paperless"
    TYPE="weekly"
    
    DEST="$RCLONE_REMOTE:$RCLONE_BACKUP_DIR/$TYPE/"
    
    [ "$DEST" = "Dropbox:Backups/Paperless/weekly/" ]
}

@test "rclone monthly backup path" {
    RCLONE_REMOTE="OneDrive"
    RCLONE_BACKUP_DIR="Backups/Paperless"
    TYPE="monthly"
    
    DEST="$RCLONE_REMOTE:$RCLONE_BACKUP_DIR/$TYPE/"
    
    [ "$DEST" = "OneDrive:Backups/Paperless/monthly/" ]
}
